name: 'Validate NPM Package Version'
description: 'Ensure that the package version you want to publish is available'
inputs:
  version-prefix:
    description: 'A prefix that will be prepended to the version.  E.g. in v1.0.0 the prefix is "v"'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
      with:
        # "fetch-depth: 0" is critical so that we get all the tags for when we check for the existence of the tag for the current version
        fetch-depth: 0 
    - id: version-check
      run: ${{ github.action_path }}/entrypoint.sh
      shell: bash
      env:
        PREFIX: ${{ inputs.version-prefix }}
    - if: ${{ failure() }}
      run: echo "The git tag ${{ steps.version-check.outputs.version }} already exists.  Did You forget to increment the version number in package.json?"
      shell: bash
